services:  
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount ke /var/www/html
      - ./vol:/var/www/html
    depends_on:
      - mysql-db
    ports:
      - 5500:5500

  # MYSQL
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: php_mysql_pass
      MYSQL_USER: admin    
      MYSQL_DATABASE: Group4-WebsitePringgading
      MYSQL_PASSWORD: admin123
    ports:
      # post mysql
      - "5501:5501"

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      # akses ke database
      - mysql-db
    ports:
      # port mysql-db
      - "5502:5502"
    environment:
      # Phpmyadmin jadi host database
      PMA_HOST: mysql-db
      # Password
      MYSQL_ROOT_PASSWORD: php_mysql_pass
