services:
  php:
    build: ./php
    ports:
      - "7002:80"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234

  mysql-db:
    build: ./mysql
    ports:
      - "7001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234

  node:
    build: ./node
    ports:
      - "7003:3000"
    depends_on:
      - mysql-db
      - php
    environment:
      DB_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_DATABASE: mkepl_task-management

volumes:
  - ./mysql/dump:/dump