version: "3.8"

services:
  app:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=tubes_task_management
    depends_on:
      - db


  db:
    container_name: mysql_container
    image: mysql:8.0
    networks:
      - mysql_network
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tubes_task_management
    ports:
      - "5501:5501"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5502:5502"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 

volumes:
  db_data:
    driver: local

networks:
  mysql_network:
    driver: bridge