name: Tubes_Deploy

on:
  push:
    branches:
      - master

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: SSH Connect
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: "${{ secrets.SERVER_PASSWORD }}"
                script: |
                  echo "(LOG) Konek..."

                  if [ ! -d "/home/afadfath/Tubes_MKEPL" ]; then
                      echo "(LOG) Directory /home/afadfath/Tubes_MKEPL tidak ada. akan dibuat."
                      mkdir -p /home/afadfath/Tubes_MKEPL
                  fi

                  cd /home/afadfath/Tubes_MKEPL

                  if [ ! -d ".git" ]; then
                      echo "(LOG) directory .git tidak ditemukan. cloning..."
                      git clone https://github.com/Afadfath03/Tubes_MKEPL .
                  fi

                  echo "(LOG) Update repo..."
                  git pull
                  git checkout master

                  echo "(LOG) compose down..."
                  docker compose down
                  
                  echo "(LOG) compose up..."
                  docker compose up -d --build
                  
                  echo "(LOG) Deployment selesai."

            - name: Dump Database from Development to Production
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                script: |
                  echo "(LOG) Konek..."  
                  if [ ! -d "/home/afadfath/Tubes_MKEPL" ]; then
                      echo "(LOG) Directory /home/afadfath/Tubes_MKEPL tidak ada. akan dibuat."
                      mkdir -p /home/afadfath/Tubes_MKEPL
                  fi
                  cd /home/afadfath/Tubes_MKEPL

                  echo "(LOG) Setting up MySQL credentials..."
                  MYSQL_USER = ${{secrets.MYSQL_USER}}
                  MYSQL_PASSWORD = ${{secrets.MYSQL_ROOT_PASSWORD}}
                  DB_Dev = ${{secrets.DEV_DB_NAME}}
                  DB_Prod = ${{secrets.PROD_DB_NAME}}

                  echo "(LOG) Dumping Development Database..."
                  mysqldump -u $MYSQL_USER -p$MYSQL_PASSWORD --no-create-db --no-create-info $DB_Dev > /home/afadfath/Tubes_MKEPL/db_devel_dump.sql

                  echo "(LOG) Restoring to Production..."
                  mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $DB_Prod < /home/afadfath/Tubes_MKEPL/db_devel_dump.sql

                  echo "(LOG) Database dump and restore completed."